project:
  type: website

website:
  title: "Jiajun Zhang Data Science Blog"
  navbar:
    right:
      - about.qmd
      - index.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/jiajun-zhang-8b794625b
      - icon: github
        href: https://github.com/AckyZhang
format:
  html:
    theme: cosmo
    css: styles.css
author: "Jiajun Zhang"
